package com.jakway.stringsgen.map;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Map;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.jakway.stringsgen.exception.DPIStringsGeneratorException;
import com.jakway.stringsgen.misc.Pair;

public class MapWriter
{
	private static final String ROOT_ELEMENT_NAME="resources",
			STRING_ELEMENT_NAME="string",
			NAME_ATTRIBUTE="name";
	private static final String STRINGS_FILENAME="strings.xml";
	private static final String BEGINNING_COMMENT="THIS FILE WAS AUTOGENERATED BY THE DPI STRINGS XML GENERATOR ON "+new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()),
								ENDING_COMMENT="END AUTOGENERATED XML";
	
	private File out=null;
	
	private ArrayList<File> stringsFiles = new ArrayList<File>();

	public MapWriter(File out)
	{
		this.out = out;
	}
	
	private Document getXMLDOMTree(ArrayList<Pair<String, String>> elements) throws ParserConfigurationException
	{
		DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		factory.setValidating(false);
		factory.setNamespaceAware(false);
		DocumentBuilder builder = factory.newDocumentBuilder();
		Document doc = builder.newDocument();
		
		//create the root node
		//Android's strings.xml doesn't use a namespace
		Element root = doc.createElement(ROOT_ELEMENT_NAME);
		doc.appendChild(doc.createComment(BEGINNING_COMMENT));
		doc.appendChild(root);
		
		for(Pair<String, String> pair : elements)
		{
			Element stringElement = doc.createElement(STRING_ELEMENT_NAME);
			//name without DPI is the general name used to reference the DPI-qualified name
			stringElement.setAttribute(NAME_ATTRIBUTE, pair.getLeft());
			
			//this isn't actually a subelement, it's the JAXP's way of setting the value of an element
			//it'll appear as <stringElement name="value_of_pair_getleft">value_of_pair_getright</stringElement>
			stringElement.appendChild(doc.createTextNode(pair.getRight()));
			
			root.appendChild(stringElement);
		}
		doc.appendChild(doc.createComment(ENDING_COMMENT));
		
		return doc;
	}
	
	private String getValuesFilenameFromDPIPrefix(String prefix)
	{
		return "values-"+prefix;
	}
	
	public void write(Map<String, ArrayList<Pair<String, String>>> map)
	{
		
		for(Map.Entry<String, ArrayList<Pair<String, String>>> entry : map.entrySet())
		{
			try {			
			Document dom = getXMLDOMTree(entry.getValue());
			
			//get the filename corresponding to the key
			String valuesFilename = getValuesFilenameFromDPIPrefix(entry.getKey());
			
			//get the values folder
			File valuesFolder = new File(out, valuesFilename);
			
			File stringsFile = new File(valuesFolder, STRINGS_FILENAME);
			
			//make the directory
			if(!valuesFolder.exists())
			{
				boolean success = valuesFolder.mkdir();
				if(!success)
					throw new DPIStringsGeneratorException("Could not create directory "+valuesFolder.toString()+"!");
			}
			else if(valuesFolder.exists() && !valuesFolder.isDirectory())
			{
				throw new DPIStringsGeneratorException(valuesFolder.toString()+" exists but is not a directory!");
			}
			
			//write the strings.xml file
			writeDOMToFile(stringsFile, dom);
			stringsFiles.add(stringsFile); //add it to the list of written files
			}
			catch(TransformerException e)
			{
				e.printStackTrace();
				throw new DPIStringsGeneratorException("TransformerException thrown while writing ArrayList to file corresponding to Map key: "+entry.getKey());
			}
			catch(ParserConfigurationException e)
			{
				e.printStackTrace();
				throw new DPIStringsGeneratorException("ParserConfigurationException thrown while writing ArrayList to file corresponding to Map key: "+entry.getKey());
			}
		}
	}
	
	private void writeDOMToFile(File stringsXMLFile, Document DOM) throws TransformerException
	{
		TransformerFactory transformerFactory = TransformerFactory.newInstance();
		Transformer transformer = transformerFactory.newTransformer();
		DOMSource domSource = new DOMSource(DOM);
		StreamResult streamResult = new StreamResult(stringsXMLFile);
		//set output options -- otherwise it gets written as an unformatted wall of text without newlines
		transformer.setOutputProperty(OutputKeys.INDENT, "yes");
		transformer.transform(domSource, streamResult);
	}
	
	public ArrayList<File> getWrittenFiles()
	{
		return stringsFiles;
	}
}